# Generated by Django 3.2.18 on 2023-11-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Gender',
            field=models.TextField(blank=True, choices=[('', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], null=True),
        ),
    ]
